version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_blog_coding_test
    container_name: laravel_blog_coding_test
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php-local.ini:/usr/local/etc/php/conf.d/php-local.ini
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    container_name: MailPit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-exa

#   nginx:
#     image: nginx:alpine
#     container_name: laravel_nginx
#     restart: unless-stopped
#     volumes:
#       - .:/var/www
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "8000:80"
#     networks:
#       - app-network

volumes:
  mysql-data:

networks:
  laravel-exa:
  app-network:
    driver: bridge
